security:
    encoders:
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    # Write here the differents roles 
    role_hierarchy:
        ROLE_ALLOWED: [ROLE_ADMIN, IS_AUTHENTICATED_ANONYMOUSLY]
        ROLE_TO_VALID: [ROLE_TO_VALID]
    firewalls:
    # Authentification (login process) and Authorization (after login process, determines your access)
    # Dev section, only for dev's toolbar
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
    #The really firewall
        main:
            anonymous: true
            
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator

            logout:
                path: app_logout

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/, roles: ROLE_ADMIN }
        # - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/admin, allow_if: "user.getConfirm() == 1" }
         - { path: ^/project/newTricks, allow_if: "user.getConfirm() == 1" }
         - { path: ^/project/edit, allow_if: "user.getConfirm() == 1" }